In [1]:
text = """ABOUT PUNE
Pune is the second largest city in the state of Maharashtra. Pune city stands bordered by the ranges of the Sahyadri Mountain. The moderate weather as well as the rich flora and fauna of the city make it an ideal travel destination. It has been known by a plethora of sobriquets. Popular among them: ‘Queen of the Deccan’, ‘Cultural capital of Maharashtra’, and ‘Oxford of the East’. It is also among the greenest urban areas in the country with more than 40 per cent of its area under green cover.

Pune is the ninth populous city of the India and one of the top 10 “Most Developed Cities” in India by GDP 2016 and one of the fastest developing cities in the Asia Pacific region. It has a very strong presence in the automobile sector and is on its way to consolidate its position as the 'Detroit of India' too. Once referred as 'Pensioner's Paradise' it is now home to many software and IT companies.

In Pune, the past meets the present. It is one of those rare cities with a twin image: that of a tradition-bound place - generally considered the quintessence of Maharashtrian culture - and that of a modern industrial metropolis.
Pune Climate
The climate of Pune is quite pleasant. Summer here begins from early March to July. Daytimes are very sunny with dry heat. Early mornings are pleasant and evenings after six, cool and breezy. Pune stands on the leeward side of the Western Ghats on an altitude of 559m. (1863 ft.).

Summers are typically hot with maximum temperatures ranging from 35℃ to 42℃. The warmest month in Pune is generally April as compared to the rest of the Deccan Plateau where it is May. Sunlight can be intense leading to skin tan and sun-burn, be sure to carry and use sunscreens. The nights in Pune are significantly cooler than most other parts in this region owing to its high altitude.

Guideline regarding clothing and conference attire:
Formal dress for Men and Women"""

In [3]:
print(text.split(" "))

['ABOUT', 'PUNE\nPune', 'is', 'the', 'second', 'largest', 'city', 'in', 'the', 'state', 'of', 'Maharashtra.', 'Pune', 'city', 'stands', 'bordered', 'by', 'the', 'ranges', 'of', 'the', 'Sahyadri', 'Mountain.', 'The', 'moderate', 'weather', 'as', 'well', 'as', 'the', 'rich', 'flora', 'and', 'fauna', 'of', 'the', 'city', 'make', 'it', 'an', 'ideal', 'travel', 'destination.', 'It', 'has', 'been', 'known', 'by', 'a', 'plethora', 'of', 'sobriquets.', 'Popular', 'among', 'them:', '‘Queen', 'of', 'the', 'Deccan’,', '‘Cultural', 'capital', 'of', 'Maharashtra’,', 'and', '‘Oxford', 'of', 'the', 'East’.', 'It', 'is', 'also', 'among', 'the', 'greenest', 'urban', 'areas', 'in', 'the', 'country', 'with', 'more', 'than', '40', 'per', 'cent', 'of', 'its', 'area', 'under', 'green', 'cover.\n\nPune', 'is', 'the', 'ninth', 'populous', 'city', 'of', 'the', 'India', 'and', 'one', 'of', 'the', 'top', '10', '“Most', 'Developed', 'Cities”', 'in', 'India', 'by', 'GDP', '2016', 'and', 'one', 'of', 'the', 'fastes

In [5]:
print(len(text.split(" ")))

331


In [7]:
import numpy as np
import tensorflow as tf                                           # handling data and deploy model
from tensorflow.keras.preprocessing.text import Tokenizer         # for preprocessing , split the text into words or subwords(tokens)

In [ ]:
# pip install --upgrade tensorflow


In [9]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])                 # tokenizer builds its vocabulary (unique words) from list of texts

In [17]:
len(tokenizer.word_index)                      # gives dictionary that maps each unique word to unique integer index 
                                               # index based on frequence of word , most frequency its index is smaller integer 

199

In [13]:
input_sequences = []                                                      # idea for model = which token come after the current token
for sentence in text.split('\n'):
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]        # converts list of texts into list of sequences of integers

  for i in range(1,len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])

In [19]:
input_sequences

[[35, 4],
 [4, 5],
 [4, 5, 1],
 [4, 5, 1, 36],
 [4, 5, 1, 36, 37],
 [4, 5, 1, 36, 37, 11],
 [4, 5, 1, 36, 37, 11, 6],
 [4, 5, 1, 36, 37, 11, 6, 1],
 [4, 5, 1, 36, 37, 11, 6, 1, 38],
 [4, 5, 1, 36, 37, 11, 6, 1, 38, 2],
 [4, 5, 1, 36, 37, 11, 6, 1, 38, 2, 39],
 [4, 5, 1, 36, 37, 11, 6, 1, 38, 2, 39, 4],
 [4, 5, 1, 36, 37, 11, 6, 1, 38, 2, 39, 4, 11],
 [4, 5, 1, 36, 37, 11, 6, 1, 38, 2, 39, 4, 11, 18],
 [4, 5, 1, 36, 37, 11, 6, 1, 38, 2, 39, 4, 11, 18, 40],
 [4, 5, 1, 36, 37, 11, 6, 1, 38, 2, 39, 4, 11, 18, 40, 15],
 [4, 5, 1, 36, 37, 11, 6, 1, 38, 2, 39, 4, 11, 18, 40, 15, 1],
 [4, 5, 1, 36, 37, 11, 6, 1, 38, 2, 39, 4, 11, 18, 40, 15, 1, 41],
 [4, 5, 1, 36, 37, 11, 6, 1, 38, 2, 39, 4, 11, 18, 40, 15, 1, 41, 2],
 [4, 5, 1, 36, 37, 11, 6, 1, 38, 2, 39, 4, 11, 18, 40, 15, 1, 41, 2, 1],
 [4, 5, 1, 36, 37, 11, 6, 1, 38, 2, 39, 4, 11, 18, 40, 15, 1, 41, 2, 1, 42],
 [4,
  5,
  1,
  36,
  37,
  11,
  6,
  1,
  38,
  2,
  39,
  4,
  11,
  18,
  40,
  15,
  1,
  41,
  2,
  1,
  42,
  43],
 [4,
  

In [21]:
max_len = max([len(x) for x in input_sequences])
max_len

90

In [23]:
# maintain consistent (same) dimension of input sequences
from tensorflow.keras.preprocessing.sequence import pad_sequences 
padded_input_sequences = pad_sequences(input_sequences, maxlen = max_len, padding='pre')

In [25]:
padded_input_sequences

array([[  0,   0,   0, ...,   0,  35,   4],
       [  0,   0,   0, ...,   0,   4,   5],
       [  0,   0,   0, ...,   4,   5,   1],
       ...,
       [  0,   0,   0, ..., 196, 197, 198],
       [  0,   0,   0, ..., 197, 198,   3],
       [  0,   0,   0, ..., 198,   3, 199]])

In [27]:
len(padded_input_sequences)               # no of input sequences

330

In [29]:
X = padded_input_sequences[:,:-1]

In [31]:
X

array([[  0,   0,   0, ...,   0,   0,  35],
       [  0,   0,   0, ...,   0,   0,   4],
       [  0,   0,   0, ...,   0,   4,   5],
       ...,
       [  0,   0,   0, ..., 195, 196, 197],
       [  0,   0,   0, ..., 196, 197, 198],
       [  0,   0,   0, ..., 197, 198,   3]])

In [33]:
X.shape

(330, 89)

In [35]:
y = padded_input_sequences[:,-1]

In [37]:
y

array([  4,   5,   1,  36,  37,  11,   6,   1,  38,   2,  39,   4,  11,
        18,  40,  15,   1,  41,   2,   1,  42,  43,   1,  44,  45,   9,
        46,   9,   1,  47,  48,   3,  49,   2,   1,  11,  50,   7,  19,
        51,  52,  53,   7,  20,  54,  55,  15,  10,  56,   2,  57,  58,
        21,  59,  60,   2,   1,  61,  62,  63,   2,  64,   3,  65,   2,
         1,  66,   7,   5,  67,  21,   1,  68,  69,  70,   6,   1,  71,
        12,  72,  22,  73,  74,  75,   2,  13,  76,  77,  78,  79,   5,
         1,  80,  81,  11,   2,   1,  23,   3,  16,   2,   1,  82,  83,
        84,  85,  86,   6,  23,  15,  87,  88,   3,  16,   2,   1,  89,
        90,  24,   6,   1,  91,  92,  25,   7,  20,  10,  26,  93,  94,
         6,   1,  95,  96,   3,   5,  17,  13,  97,   8,  98,  13,  99,
         9,   1, 100,   2, 101, 102, 103, 104,   9, 105, 106,   7,   5,
       107, 108,   8, 109, 110,   3,   7, 111,   4,   1, 112, 113,   1,
       114,   7,   5,  16,   2, 115, 116,  24,  12,  10, 117, 11

In [39]:
y.shape

(330,)

In [41]:
len(tokenizer.word_index)             

199

In [43]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes=len(tokenizer.word_index)+1)          # like one hot encoded

In [45]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [47]:
y.shape

(330, 200)

In [49]:
max_len

90

In [53]:
from tensorflow.keras.models import Sequential                # create linear stack of layers
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [55]:
# model building
model = Sequential()
model.add(Embedding(len(tokenizer.word_index)+1, 100, input_shape=((max_len)-1,)))
model.add(LSTM(150))
model.add(Dense(len(tokenizer.word_index)+1, activation='softmax'))

C:\Users\pavan\anaconda\envs\llm_env\lib\site-packages\keras\src\layers\core\embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [57]:
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

In [59]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ (None, 89, 100)             │          20,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ (None, 150)                 │         150,600 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 200)                 │          30,200 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 200,800 (784.38 KB)

 Trainable params: 200,800 (784.38 KB)

 Non-trainable params: 0 (0.00 B)

In [61]:
model.fit(X,y,epochs=100)                            # model training

Epoch 1/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 7s 123ms/step - accuracy: 0.0204 - loss: 5.2952
Epoch 2/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 116ms/step - accuracy: 0.0899 - loss: 5.1431
Epoch 3/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 120ms/step - accuracy: 0.0929 - loss: 4.8795
Epoch 4/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 111ms/step - accuracy: 0.0733 - loss: 4.8557
Epoch 5/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 113ms/step - accuracy: 0.0777 - loss: 4.8119
Epoch 6/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 114ms/step - accuracy: 0.0926 - loss: 4.8176
Epoch 7/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 112ms/step - accuracy: 0.0672 - loss: 4.8576
Epoch 8/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 122ms/step - accuracy: 0.0845 - loss: 4.6896
Epoch 9/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 112ms/step - accuracy: 0.0915 - loss: 4.6386
Epoch 10/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 117ms/step - accuracy: 0.0865 - loss: 4.5083
Epoch 11/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 113ms/step - accuracy: 0.1087 - loss: 4.5218
Epoch 12/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1

In [63]:
# model testing
import time
text = "Pune is the "

for i in range(10):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=max_len-1, padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 514ms/step
Pune is the  second
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 193ms/step
Pune is the  second largest
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step
Pune is the  second largest city
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step
Pune is the  second largest city in
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step
Pune is the  second largest city in the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step
Pune is the  second largest city in the state
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step
Pune is the  second largest city in the state of
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step
Pune is the  second largest city in the state of maharashtra
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step
Pune is the  second largest city in the state of maharashtra pune
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step
Pune is the  second largest city in the state of maharashtra pune city


In [65]:
import time
text = "Pune city "

for i in range(20):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=max_len-1, padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step
Pune city  the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step
Pune city  the second
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 178ms/step
Pune city  the second largest
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step
Pune city  the second largest city
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step
Pune city  the second largest city in
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step
Pune city  the second largest city in the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step
Pune city  the second largest city in the state
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step
Pune city  the second largest city in the state of
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step
Pune city  the second largest city in the state of maharashtra
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step
Pune city  the second largest city in the state of maharashtra pune
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
Pune city  the second largest city in the state of maharashtra pune city
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step
Pune city  the second largest city in the state

In [67]:
import time
text = "which are favourite places in pune"

for i in range(10):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=max_len-1, padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step
which are favourite places in pune the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step
which are favourite places in pune the past
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step
which are favourite places in pune the past meets
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step
which are favourite places in pune the past meets the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step
which are favourite places in pune the past meets the present
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step
which are favourite places in pune the past meets the present it
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step
which are favourite places in pune the past meets the present it is
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step
which are favourite places in pune the past meets the present it is one
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step
which are favourite places in pune the past meets the present it is one of
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step
which are favourite places in pune the past meets the present it is one of those
